_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 3 # prevents early stopping
max_epochs: 50

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1
log_every_n_steps: 34

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
gradient_clip_val: 0
accumulate_grad_batches: 1
auto_lr_find: False