
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

prepare: ## Download and prepare datasets 
	python src/prepare.py datamodule.audio.preparers.ncs_preparer.download=True datamodule.audio.preparers.ncs_preparer.split=True

train: ## Train the model
	python src/train.py

test-default: ## Test model by running 1 full epoch
	python src/train.py debug=fdr

test-overfit: ## Test model by running 1 train, val and test loop, using only 1 batch
	python src/train.py debug=overfit

test-fdr: ## Test model with overfit on 1 batch
	python src/train.py debug=fdr

test-limit: ## Test model by running train on 1% of data
	python src/train.py debug=limit

debug: ## Enter debugging mode with pdb
	#
	# tips:
	# - use "import pdb; pdb.set_trace()" to set breakpoint
	# - use "h" to print all commands
	# - use "n" to execute the next line
	# - use "c" to run until the breakpoint is hit
	# - use "l" to print src code around current line, "ll" for full function code
	# - docs: https://docs.python.org/3/library/pdb.html
	#
	python -m pdb src/train.py debug=default
