
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

install:
	chmod +rwx scripts/install.sh && scripts/install.sh

prepare-audio: ## Download and prepare datasets 
	python src/scripts/prepare-audio.py \
		datamodule.audio.preparers.ncs_preparer.download=True \
		datamodule.audio.preparers.ncs_preparer.split=True \
		datamodule.audio.preparers.gs_mtg_preparer.download=True \
		datamodule.audio.preparers.gs_mtg_preparer.split=True \
		datamodule.audio.preparers.gs_key_preparer.download=True \
		datamodule.audio.preparers.gs_key_preparer.split=True

prepare-ncs-audio: ## Download and prepare NCS dataset
	python src/scripts/prepare-audio.py \
		datamodule.audio.preparers.ncs_preparer.download=True \
		datamodule.audio.preparers.ncs_preparer.split=True \

prepare-gs-mtg-audio: ## Download and prepare GS MTG dataset
	python src/scripts/prepare-audio.py \
		datamodule.audio.preparers.gs_mtg_preparer.download=True \
		datamodule.audio.preparers.gs_mtg_preparer.split=True

prepare-gs-key-audio: ## Download and prepare GS KEY dataset
	python src/scripts/prepare-audio.py \
		datamodule.audio.preparers.gs_key_preparer.download=True \
		datamodule.audio.preparers.gs_key_preparer.split=True

prepare-images:
	python src/scripts/prepare_images.py \
	datamodule.image.download=True

create-spectrograms: ## Saves spectrogram images from existing audio datasets
	python src/scripts/create_spectrograms.py 

prepare-spectrograms: ## Downloads audio data and creates spectrograms from downloaded data
	python src/scripts/create_spectrograms.py \
		datamodule.audio.preparers.ncs_preparer.download=True \
		datamodule.audio.preparers.ncs_preparer.split=True \
		datamodule.audio.preparers.gs_mtg_preparer.download=True \
		datamodule.audio.preparers.gs_mtg_preparer.split=True \
		datamodule.audio.preparers.gs_key_preparer.download=True \
		datamodule.audio.preparers.gs_key_preparer.split=True

eval: ## Train the model
	python src/eval.py

train: ## Train the model
	python src/train.py

test-default: ## Test model by running 1 full epoch
	python src/train.py debug=fdr

test-overfit: ## Test model by running 1 train, val and test loop, using only 1 batch
	python src/train.py debug=overfit \
	logger=tensorboard \
    datamodule.image.batch_size=32

test-fdr: ## Test model with overfit on 1 batch
	python src/train.py debug=fdr

test-limit: ## Test model by running train on 1% of data
	python src/train.py debug=limit

debug: ## Enter debugging mode with pdb
	#
	# tips:
	# - use "import pdb; pdb.set_trace()" to set breakpoint
	# - use "h" to print all commands
	# - use "n" to execute the next line
	# - use "c" to run until the breakpoint is hit
	# - use "l" to print src code around current line, "ll" for full function code
	# - docs: https://docs.python.org/3/library/pdb.html
	#
	python -m pdb src/train.py debug=default
