gs_mtg_dataset:
  target: src.datamodules.common.dataset.audio_dataset_folder.AudioDatasetFolder
  root_dir: ${paths.gs_mtg_root_dir}
  transform: ${datamodule.audio.transform}
  extensions: ${datamodule.audio.extensions}
  device: ${trainer.accelerator}
  interval_length: ${datamodule.audio.interval_length}
  sr: ${datamodule.audio.sr}
  loader_type: ${datamodule.audio.loader_type}
