ncs_test_dataset:
  target: src.datamodules.common.dataset.audio_dataset_folder.AudioDatasetFolder
  root_dir: ${paths.ncs_test_dir}
  transform: ${datamodule.audio.transform}
  extensions: ${datamodule.audio.extensions}
  device: ${trainer.device}
  interval_length: ${datamodule.audio.interval_length}
  sr: ${datamodule.audio.sr}
