_target_: src.datamodules.audio_datamodule.AudioDataModule
batch_size: 4
num_workers: 0
pin_memory: False
sr: 44100
extensions: ['.wav', '.mp3', '.flac', '.ogg']
interval_length: 30

transform:
  _target_: nnAudio.features.cqt.CQT
  hop_length: 512
  sr: ${datamodule.audio.sr}
  verbose: False
  n_bins: 84
  bins_per_octave: 12

defaults:
  - test_datasets:
      - ncs_test_dataset
      - gs_key_dataset
  - train_datasets:
      - ncs_train_dataset
      - gs_mtg_dataset
  - preparers:
      - ncs_preparer
      - gs_mtg_preparer
      - gs_key_preparer
