_target_: src.datamodules.audio_datamodule.AudioDataModule
batch_size: 16
num_workers: 0
pin_memory: False
sr: 44100
extensions: ['.wav', '.mp3', '.flac', '.ogg']
interval_length: 30
loader_type: 'audiofile' # 'audiofile' or 'torch' - 'torch' needs lots of different dependencies, omit using it

transform:
  _target_: nnAudio.features.cqt.CQT
  hop_length: 2048
  sr: ${datamodule.audio.sr}
  verbose: False
  n_bins: 120
  bins_per_octave: 24
  fmin: 65.41

defaults:
  - test_datasets:
      - ncs_test_dataset
      - gs_key_dataset
  - train_datasets:
      - ncs_train_dataset
      - gs_mtg_dataset
  - preparers:
      - ncs_preparer
      - gs_mtg_preparer
      - gs_key_preparer
