_target_: src.datamodules.audio_datamodule.AudioDataModule
batch_size: 4
num_workers: 0
pin_memory: False
sr: 44100
extensions: ['.wav', '.mp3', '.flac', '.ogg']
interval_length: 30

transform:
  _target_: nnAudio.features.cqt.CQT
  hop_length: 512
  sr: ${datamodule.audio.sr}
  verbose: False
  n_bins: 84
  bins_per_octave: 12

# datasets:
#   - train:
#     ncs_train_dataset:
#       target: src.datamodules.common.dataset.audio_dataset_folder.AudioDatasetFolder
#       root_dir: ${datamodule.audio.train_dir}
#       transform: ${datamodule.audio.transform}
#       extensions: ${datamodule.global_extensions}

#   test:
#     ncs_test_dataset:
#       target: src.datamodules.common.dataset.audio_dataset_folder.AudioDatasetFolder
#       root_dir: ${datamodule.audio.test_dir}
#       transform: ${datamodule.audio.transform}
#       extensions: ${datamodule.global_extensions}

# preparers:
#   ncs_preparer:
#     _target_: src.datamodules.ncs.preparer.preparer.NCSPreparer
#     root_dir: ${datamodule.audio.root_dir}
#     train_dir: ${datamodule.audio.train_dir}
#     test_dir: ${datamodule.audio.test_dir}
#     train_ratio: 0.85
#     download: False # Downloads saved version from google drive with id below
#     google_id: '1XF7lCWlr8RjSeCUZ2FBaGkSdTNRxuWLV'
#     create: False # Creates dataset from scratch
#     interval_length: 10

defaults:
  - test_datasets:
      - ncs_test_dataset
      - gs_key_dataset
  - train_datasets:
      - ncs_train_dataset
      - gs_mtg_dataset
  - preparers:
      - ncs_preparer
      - gs_mtg_preparer
      - gs_key_preparer
