_target_: src.datamodules.audio_datamodule.AudioDataModule
batch_size: 16
num_workers: 0
pin_memory: False
sr: 44100
extensions: ['.wav', '.mp3', '.flac', '.ogg']
interval_length: 30
loader_type: 'audiofile' # 'audiofile' or 'torch' - 'torch' needs lots of different dependencies, omit using it
device: ${trainer.accelerator}

transform:
  _target_: nnAudio.features.cqt.CQT
  hop_length: 2048
  sr: ${datamodule.audio.sr}
  verbose: False
  n_bins: 120
  bins_per_octave: 24
  fmin: 65.41

audio_dir: ${paths.audio_dir}

images_dir: ${paths.images_dir}
images_preparers:
  ncs_test:
    images_dir: ${paths.ncs_images_test_dir}
    dataset_name: 'ncs_train_dataset'
  ncs_train:
    images_dir: ${paths.ncs_images_train_dir}
    dataset_name: 'ncs_test_dataset'
  gs_mtg:
    images_dir: ${paths.gs_mtg_images_dir}
    dataset_name: 'gs_mtg_dataset'
  gs_key:
    images_dir: ${paths.gs_key_images_dir}
    dataset_name: 'gs_key_dataset'

torch_dir: ${paths.torch_dir}

defaults:
  - test_datasets:
      - ncs_test_dataset
      - gs_key_dataset
  - train_datasets:
      - ncs_train_dataset
      - gs_mtg_dataset
  - preparers:
      - ncs_preparer
      - gs_mtg_preparer
      - gs_key_preparer
