_target_: src.models.audio_classifier.AudioClassifier
learning_rate: 0.001

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

model:
  _target_: src.models.components.allconv.AllConv
  num_feature_maps,: 2
  dropout_rate: 0.1
  input_channels: 1
  num_classes: 24
