_target_: src.models.key_classifier.KeyClassifier
learning_rate: 0.001

defaults:
  - criterion: mirex_v0 # or v1 or v2 or cross_entropy
  - model: cqt_allconv # or allconv or allconv_rnn or cqt_allconv_rnn

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.4
  patience: 2
