# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# Datasets
data_dir: ${paths.root_dir}/data/

# NCS
ncs_root_dir: ${paths.root_dir}/data/ncs
ncs_train_dir: ${paths.ncs_root_dir}/train/
ncs_test_dir: ${paths.ncs_root_dir}/validation/

# GS MTG
gs_mtg_root_dir: ${paths.root_dir}/data/gs_mtg

# GS Key
gs_key_root_dir: ${paths.root_dir}/data/gs_key

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
