# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# ******** Datasets ********
# ======== Audio ===========
data_dir: ${paths.root_dir}/data/

# NCS
ncs_root_dir: ${paths.root_dir}/data/ncs
ncs_train_dir: ${paths.ncs_root_dir}/train/
ncs_test_dir: ${paths.ncs_root_dir}/validation/

# GS MTG
gs_mtg_root_dir: ${paths.root_dir}/data/gs_mtg

# GS Key
gs_key_root_dir: ${paths.root_dir}/data/gs_key

# ======== Images ===========
images_dir: ${paths.root_dir}/data/images

# NCS
ncs_images_root_dir: ${paths.images_dir}/ncs
ncs_images_train_dir: ${paths.ncs_images_root_dir}/train/
ncs_images_test_dir: ${paths.ncs_images_root_dir}/validation/

# GS MTG
gs_mtg_images_dir: ${paths.images_dir}/gs_mtg

# GS Key
gs_key_images_dir: ${paths.images_dir}/gs_key

# ======== Audio Tensors ===========
torch_dir: ${paths.root_dir}/data/torch-audio

# NCS
ncs_torch_root_dir: ${paths.torch_dir}/ncs
ncs_torch_train_dir: ${paths.ncs_torch_root_dir}/train/
ncs_torch_test_dir: ${paths.ncs_torch_root_dir}/validation/

# GS MTG
gs_mtg_torch_dir: ${paths.torch_dir}/gs_mtg

# GS Key
gs_key_torch_dir: ${paths.torch_dir}/gs_key

# ******** Logs ********
# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
