gs_key_preparer:
  _target_: src.datamodules.gs_key.preparer.gs_key_preparer.GS_KeyPreparer
  data_dir: ${paths.data_dir}
  root_dir: ${paths.gs_key_root_dir}

  extensions: ${datamodule.audio.extensions}

  download: False # Downloads saved version from google drive with id below

  download_type: ${constants.gs_key_host}
  download_id: ${constants.gs_key_id}
  keys_download_id: ${constants.gs_key_keys_id}
  zip_filename: 'data/gs_key-dataset.zip'
  keys_zip_filename: 'data/gs_key-dataset-keys.zip'

  split: False # splits all audio files into intervals with length:
  interval_length: ${datamodule.audio.interval_length}
