gs_mtg_preparer:
  _target_: src.datamodules.gs_mtg.preparer.gs_mtg_preparer.GS_MTGPreparer
  data_dir: ${paths.data_dir}
  root_dir: ${paths.gs_mtg_root_dir}

  extensions: ${datamodule.audio.extensions}

  download: False # Downloads saved version from google drive with id below

  google_id: '1GRNO_PK8xGZIczzhcs2vPtIsO6SR6DSq'
  annotations_google_id: '1hGhXxHw3cmsr0ZoyxiEbrKdOi3hkTWI6' # small version 400MB
  zip_filename: 'data/gs_mtg-dataset.zip'
  annotations_filename: 'annotations.txt'

  split: False # splits all audio files into intervals with length:
  interval_length: ${datamodule.audio.interval_length}
