ncs_preparer:
  _target_: src.datamodules.ncs.preparer.ncs_preparer.NCSPreparer
  data_dir: ${paths.audio_dir}
  root_dir: ${paths.ncs_root_dir}
  train_dir: ${paths.ncs_train_dir}
  test_dir: ${paths.ncs_test_dir}
  train_ratio: 0.85

  extensions: ${datamodule.audio.extensions}

  download: False # Downloads saved version from google drive with id below

  download_type: ${constants.ncs_host}
  download_id: ${constants.ncs_id}
  zip_filename: 'data/ncs-dataset.zip'

  create: False # Creates dataset from scratch

  split: False # splits all audio files into intervals with length:
  interval_length: ${datamodule.audio.interval_length}
