# @package _global_

defaults:
  - _self_
  - datamodule: default.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: key.yaml
  - logger: null
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - constants: default.yaml

task_name: 'eval'
full: False

tags: ['dev']

# temporary
ckpt_path: ${paths.root_dir}/checkpoints/best.ckpt

# Chooses audio or image datamodules
datamodule_type: 'tensor' # 'audio' or 'image'
