global_sr: 44100
global_extensions: ['wav', 'flac', 'mp3', 'ogg']

defaults:
  - ncs.yaml
  - mnist.yaml
  - _self_

ncs:
  sr: ${datamodule.global_sr}
  # extensions: ${datamodule.global_extensions}
